// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcI19ayqN22GbYOlMCjzOt5ci219spko',
    appId: '1:161895635424:web:3b0f4fc03b9d775106f385',
    messagingSenderId: '161895635424',
    projectId: 'productos-test-1212c',
    authDomain: 'productos-test-1212c.firebaseapp.com',
    storageBucket: 'productos-test-1212c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwIVpnbQRnlpT1PfU1mRjnqFQee-mdA_8',
    appId: '1:161895635424:android:68f46bc359e4138606f385',
    messagingSenderId: '161895635424',
    projectId: 'productos-test-1212c',
    storageBucket: 'productos-test-1212c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9X5PEh-mMLmtfIy0jZ_Pjj_Wf1wG4NoU',
    appId: '1:161895635424:ios:623c05c1293cd74e06f385',
    messagingSenderId: '161895635424',
    projectId: 'productos-test-1212c',
    storageBucket: 'productos-test-1212c.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9X5PEh-mMLmtfIy0jZ_Pjj_Wf1wG4NoU',
    appId: '1:161895635424:ios:623c05c1293cd74e06f385',
    messagingSenderId: '161895635424',
    projectId: 'productos-test-1212c',
    storageBucket: 'productos-test-1212c.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlcI19ayqN22GbYOlMCjzOt5ci219spko',
    appId: '1:161895635424:web:dd7deb8b7256e3aa06f385',
    messagingSenderId: '161895635424',
    projectId: 'productos-test-1212c',
    authDomain: 'productos-test-1212c.firebaseapp.com',
    storageBucket: 'productos-test-1212c.firebasestorage.app',
  );

}